// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAexYqdI0GfBjt7rIyiGntsW3L1bvqbbLI',
    appId: '1:535312670815:web:918317dd16ae34482dbbea',
    messagingSenderId: '535312670815',
    projectId: 'todoapps-4518e',
    authDomain: 'todoapps-4518e.firebaseapp.com',
    storageBucket: 'todoapps-4518e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH7v-IZ7W7TL9oBZEw4fVNaxQWi2ZmOZo',
    appId: '1:535312670815:android:add63d6c61336d5d2dbbea',
    messagingSenderId: '535312670815',
    projectId: 'todoapps-4518e',
    storageBucket: 'todoapps-4518e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu8LnZVpAfnm9HMNtDxDi9lMnHFccYzeg',
    appId: '1:535312670815:ios:a02a3d48cf785f3a2dbbea',
    messagingSenderId: '535312670815',
    projectId: 'todoapps-4518e',
    storageBucket: 'todoapps-4518e.appspot.com',
    iosBundleId: 'com.example.crudoperation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu8LnZVpAfnm9HMNtDxDi9lMnHFccYzeg',
    appId: '1:535312670815:ios:c5f6b92cb6f118572dbbea',
    messagingSenderId: '535312670815',
    projectId: 'todoapps-4518e',
    storageBucket: 'todoapps-4518e.appspot.com',
    iosBundleId: 'com.example.crudoperation.RunnerTests',
  );
}
